### ISSUE TITLE
Having a header or notes cause the parser to fail

### ISSUE THREAD

**Issue by cprass** [osk/node-webvtt#10]
Using one of the examples from MDN:

```
WEBVTT - Translation of that film I like

NOTE
This translation was done by Kyle so that
some friends can watch it with their parents.

1
00:02:15.000 --> 00:02:20.000
- Ta en kopp varmt te.
- Det är inte varmt.

2
00:02:20.000 --> 00:02:25.000
- Har en kopp te.
- Det smakar som te.  

NOTE This last line may not translate well.

3
00:02:25.000 --> 00:02:30.000
- Ta en kopp
```

That's the parser output:
```
ParserError: "Cue identifier needs to be followed by timestamp (cue #0)"
```

**Comment by osk** [comment]
Thanks for the report. I'll look into this shortly.

**Comment by ApayRus** [comment]
It happens again. But without extra message. just `Error {}` in console.log. 
I mean heading info...

**Comment by ApayRus** [comment]
> It happens again. But without extra message. just `Error {}` in console.log.
> I mean heading info...

I'm sorry, I have noticed options = {meta:true}

**Comment by osk** [comment]
@Aparus all good? OK to close?

**Comment by ApayRus** [comment]
> @Aparus all good? OK to close?

yes. it works ) thank you. I'll open new issue with my proposals ;-)
