### ISSUE TITLE
[Feature Suggestion] WebVTT exporter

### ISSUE THREAD

**Issue by goatandsheep** [osk/node-webvtt#11]
I'm open to contributing to this project to add an exporter. My idea is that users can parse the WebVTT file, modify it, then export it back to WebVTT format.

**Comment by osk** [comment]
Can you elaborate? It sounds like a new project that could use this one for parsing.

**Comment by goatandsheep** [comment]
I need to create an online vtt editor. For that, i need to take in vtt text, convert that into an editable data model, e.g. your parsed object, and after modification, export it back to vtt.

It does seem to be "a new project that could use this for parsing", but i feel the project could benefit from it either way. Feel free to disagree :smile:

**Comment by osk** [comment]
Originally the parser was secondary to the creation of the HLS playlists, so adding more utility isn't at all bad. Feel free to open a PR.

**Comment by osk** [comment]
Added via #15
