### ISSUE TITLE
Hours timestamp should support more than 2 digits

### ISSUE THREAD

**Issue by slifty** [osk/node-webvtt#117]
The [WebVTT spec](https://www.w3.org/TR/webvtt1/#webvtt-timestamp) says that the timesttamps should be:

> A WebVTT timestamp consists of the following components, in the given order:
>    Optionally (required if hours is non-zero):
>         Two or more [ASCII digits](https://www.w3.org/TR/html51/infrastructure.html#ascii-digits), representing the hours as a base ten integer.

Right now any hours longer than 2 digits are truncated to only include the final two digits of the hours count.

**Comment by slifty** [comment]
Thank you @goatandsheep for merging!

@osk do you know if you will be planning to release an updated build with this change?

**Comment by osk** [comment]
@slifty v1.9.4 released now, thank you!
