### ISSUE TITLE
[Suggestion] Add an option for parsing without <v> tags?

### ISSUE THREAD

**Issue by jesse-lee-loom** [osk/node-webvtt#122]
Sometimes vtt has voice tags (`<v> ... </v>`), which are helpful for trying to stylize the expression of a sound. When you don't want them, however, they're very difficult to remove without adding some other parsing library for xml-like objects. Can `node-webvtt` offer an option where v-tags are ignored?

**Comment by osk** [comment]
@jesse-lee-loom do you have a full test case for this or a reference to how it behaves?

**Comment by osk** [comment]
Since this would require the package to take on a xml dependency, which I'd rather not add.
