### ISSUE TITLE
Region not recognized

### ISSUE THREAD

**Issue by goatandsheep** [osk/node-webvtt#13]
[This example with regions](https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/region.html#example-webvtt-file-with-regions) gives the following error:

> ParserError: No blank line after signature

**Comment by osk** [comment]
The file you reference states at top:
"THIS DOCUMENT IS OUT-DATED, THE CONTENT HAS BEEN MERGED INTO THE WEBVTT SPEC. IT MERELY EXISTS FOR REFERENCE PURPOSES." and the webvtt doesn't include any examples in its [definition of regions](https://w3c.github.io/webvtt/#regions). Also, my reference, [webvtt validator](https://quuz.org/webvtt/) gives error for the example.

Do you have more insight into it? I have limited time at the moment to read through the spec and confirm what's what.

**Comment by goatandsheep** [comment]
Ahh yes you're right that there are few examples and none on the spec sheet. [The validator that you're using does have an open PR for regions which is pending](https://github.com/annevk/webvtt/pull/6). I'll keep looking into it and let you know if i find something more concrete.

**Comment by goatandsheep** [comment]
I think we can lay off it for a while, since it's still only in [Candidate Recommendation](https://www.w3.org/TR/webvtt1/#css-extensions-introduction) stage.
