### ISSUE TITLE
Automated testing / code coverage

### ISSUE THREAD

**Issue by goatandsheep** [osk/node-webvtt#14]
I noticed in the TODO you wanted to have code coverage setup. I want to setup:

* Automated Testing: [TravisCI](https://travis-ci.com/)
* Code Coverage: [Coveralls](https://coveralls.io/)

**Comment by goatandsheep** [comment]
Can we also do this on [precommit](https://www.npmjs.com/package/pre-commit)?

**Comment by osk** [comment]
Yes, feel free to add it in a PR

**Comment by osk** [comment]
Added circleci
