### ISSUE TITLE
[Feature Suggestion] Ignore extra header lines

### ISSUE THREAD

**Issue by abstractvector** [osk/node-webvtt#18]
I'm using this module to ingest data from Google's [YouTube Captions API](https://developers.google.com/youtube/v3/docs/captions/download). Unfortunately, the content it generates has extra lines after the opening `WEBVTT` line, for example:

```
WEBVTT
Kind: captions
Language: en

00:00:00.000 --> 00:00:00.960
[Happy music]
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API), this is not allowed, however nonetheless it appears there. At the moment I'm solving this with a workaround to alter the string before passing it to `parse()`:

```js
const adjustedCaption = caption.replace(/^WEBVTT[\s\S]*?\n\n/, "WEBVTT\n\n");
```

Without this workaround, I receive an error: `Missing blank line after signature`. It would be preferable if this module could instead accept an option to ignore trailing signature lines. Looking at the code, this wouldn't have adverse effects on the parsing. Alternatively, these lines could be parsed and added as metadata to the parsed output.

I'd be happy to issue a PR for this if you're comfortable with the approach, or if you have a better suggestion I can look at implementing that too.

**Comment by osk** [comment]
Hi @abstractvector, that sounds like a fine way to go about it and I'd be happy to merge a PR.

**Comment by abstractvector** [comment]
@osk would you be happy if I go the route of exposing the fields as an extra top-level object called `meta`? In the case of my example above, `parse()` would return something like:

```js
{
  "valid": true,
  "meta": {
    "Kind": "captions",
    "Language": "en"
  },
  "cues": [
    // ..
  ]
}
```

**Comment by osk** [comment]
Looks like this is something being added via the webm project:
http://wiki.webmproject.org/webm-metadata/temporal-metadata/webvtt-metadata
but that's just after a few minutes of research.

It should be fine if `webvtt.parse(input);` would get an options param so e.g. `webvtt.parse(input, { meta: true });` would look for these meta fields and add them to the output. If the param is passed but no metadata found, it should return `"meta": null` or something to that effect.

**Comment by abstractvector** [comment]
@osk Sounds great! I'm not an expert on this topic by any means, so I appreciate the steer! I'll work on a PR for it.
