### ISSUE TITLE
VTT Subs go out of sync when translate from EN to ES.

### ISSUE THREAD

**Issue by bySabi** [osk/node-webvtt#27]
@osk  I have this problem with `node-webvtt`

I first parse the English VTT file, translate the text and replace it within the object cue, and then compile the VTT file back.
It works very well but I have noticed that in the resulting file the starting time of the paragraphs is not exactly the same. In the paragraphs of the beginning of the file the difference is small but it accumulates and at the end of the file there are differences of up to 1 minute.

I put original and translate file on a shared driver: 

The update cue it's done here: https://github.com/bySabi/subs-translate/blob/master/bin/subs-translate#L299

Thanks for this wonderful module.

**Comment by bySabi** [comment]
It seems that the problem is not in `node-webvtt`

I will close this for now
sorry :-(

**Comment by osk** [comment]
Thanks! Hope you figure out your issue :)
