### ISSUE TITLE
Handle STYLE blocks

### ISSUE THREAD

**Issue by jaimefps** [osk/node-webvtt#29]
It seems that the library doesn't currently parse the styling blocks.

See section titled `Within the WebVTT file itself`:
https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API

**Comment by 1c7** [comment]
May I ask any update?

**Comment by 1c7** [comment]
@jaimefps  did you solve the problem?

I got problem 
```
WEBVTT
Kind: captions
Language: en

00:00:00.180 --> 00:00:03.760
Thanks to Curiosity Stream for supporting
PBS Digital Studios.

```
Error

```
➜  test git:(master) ✗ node 6.vtt.js

/Users/remote_edit/Documents/Translate-Subtitle-File/app/node_modules/node-webvtt/lib/parser.js:54
    throw new ParserError('Missing blank line after signature');
    ^
Error: Missing blank line after signature
```

```
WEBVTT

00:00:00.180 --> 00:00:03.760
Thanks to Curiosity Stream for supporting
PBS Digital Studios.

```
success

why can't this lib just ignore:
```
Kind: captions
Language: en
```

**Comment by CarlosJimenez** [comment]
You could consider passing  meta:true as parameter

const parsed = webvtt.parse(input, { meta: true });

**Comment by 1c7** [comment]
@CarlosJimenez 
Thank you! it works!

**Comment by CarlosJimenez** [comment]
Glad to help
Maybe you should close the issue.

**Comment by 1c7** [comment]
@CarlosJimenez 
I can't, I didn't open this issue. @jaimefps  did

**Comment by CarlosJimenez** [comment]
Good point 😂

**Comment by jaimefps** [comment]
Thanks for the answers!
