### ISSUE TITLE
cue content causing 'ParserError', due to empty lines

### ISSUE THREAD

**Issue by ajmas** [osk/node-webvtt#4]
I have extracted a subtitle track, as webvtt, from an MPEG4 file (from Contour+2 camera), using ffmpeg. Due to empty lines in the text of 'cue' block this is causing the following exception:

```
.../node_modules/node-webvtt/lib/parser.js:65
    throw new ParserError(msg);
    ^
Error: Cue identifier needs to be followed by timestamp (cue #1)
```

With a sample data from the webvtt file being:

```
WEBVTT

00:00.000 --> 00:01.000
FW version:1700 V2.1.29
FW name: ContourPlus2

UPDATE:N
UPDATE_FW:N

    SWITCH_1
1RES:D
1BR:H
1EV:0
1SHRP:3
1AE:C
1CTST:62
1MIC:45
1EXT_MIC:30
1SILENT:1
1LSR:1
1LED:0
1GPS_PWR:0
1GPS_REC:1
1AWB:0

    SWITCH_2
2RES:A
2BR:H
2EV:0
2SHRP:3
2AE:C
2CTST:62
2MIC:45
2EXT_MIC:30
2SILENT:0
2LSR:0
2LED:0
2GPS_PWR:0
2GPS_REC:1
2AWB:0
```

Is there any way we can get node-webvtt to deal with this? The current thought being to require all cue block be empty + properly formatted start/end time line and then treating the rest as cue content? I haven't read enough of the WebVTT spec to know whether this would cause issue.

**Comment by ajmas** [comment]
At the moment I have the following draft code which helps resolve the issue:

```
  const CUE_HEADER_REGEXP = /(\d\d\:\d\d[.,]\d\d\d)\s-->\s(\d\d\:\d\d[.,]\d\d\d)/;

  const lines = input.split('\n');
  var parts = [];
  var text = '', checkCueHeader, i=0;

  console.log(lines[i]);
  if (!lines[0].startsWith('WEBVTT')) {
    throw new ParserError('Must start with "WEBVTT"');
  }

  const headerParts = lines[0].split('\n');

  for (i=1; i<lines.length; i++) {
    if (lines[i].length == 0) {
      checkCueHeader = true;
      continue;
    }
    if (checkCueHeader && CUE_HEADER_REGEXP.test(lines[i])) {
      parts.push(text);
      text = '';
    }
    text += lines[i] + '\n';
    checkCueHeader = false;
  }
```

**Comment by osk** [comment]
I'm using this parser as a reference:
https://quuz.org/webvtt/
along with `mediasubtitlesegmenter` from Apple.

Both of those fail on your example, but they do not if the consecutive newlines are removed:

```
FW name: ContourPlus2

UPDATE:N
UPDATE_FW:N

    SWITCH_1
```

becomes

```
FW name: ContourPlus2
UPDATE:N
UPDATE_FW:N
    SWITCH_1
```

Doing a bit of research, these are probably cue settings, as per the spec here:
https://w3c.github.io/webvtt/#webvtt-cue-block

What's your use case? The original implementation was only thought to split subtitles for HLS streams 😄

**Comment by kthelgason** [comment]
@ajmas The example WebVTT file you've provided is invalid. 

According to the spec:

> A WebVTT cue settings list consist of a sequence of zero or more WebVTT cue settings in any order, separated from each other by one or more U+0020 SPACE characters or U+0009 CHARACTER TABULATION (tab) characters.

Cue settings can not be separated by newlines.

**Comment by ajmas** [comment]
what the firmware on the camera is doing is adding the configuration file as a subtitle track. I am trying to convert that track into a text based subtitle, based on the supported export approaches supported by ffmpeg, so I can do further processing. I chose webvtt, but then discovered this limitation. This is probably an edge case not thought of during the design of the spec? Maybe ffmpeg should be specifying the newlines as \n?

Worst case I may just fork and add a 'lenient mode' for my needs, until I find a better solution.

**Comment by osk** [comment]
As @kthelgason points out, the cues are invalid because they are separated by a newline. So I agree with a `wontfix` here.

However, you could pre-process the files to remove newlines from cues or find a way fo make ffmpeg not spit them out? And then you could parse them and post-process the headers?

**Comment by kthelgason** [comment]
@ajmas It sounds like what you're doing is a bit of a "hack" and not exactly a common use-case that we should make an effort to support. I think your suggestion of customising a fork to your needs is the way to go.
