### ISSUE TITLE
Parser doesn't respect timestamps with single digit hours

### ISSUE THREAD

**Issue by alecananian** [osk/node-webvtt#8]
The regular expression supplied for matching a WebVTT timestamp does not allow for a timestamp that denotes the hour number with a single digit:

**Regular Expression**

    const TIMESTAMP_REGEXP = /([0-9]{2})?:?([0-9]{2}):([0-9]{2}\.[0-9]{3})/;

**Example timestamps**

    59:58.000 --> 59:59.000
    <b>(GASPS) Hunter?</b>
    
    1:00:00.000 --> 1:00:01.000
    <b>You're fired!</b>

However according to the [WebVTT spec](https://w3c.github.io/webvtt/#cue-timings-and-settings-parsing) and its description of [how to parse a timestamp](https://w3c.github.io/webvtt/#collect-a-webvtt-timestamp), a parser should allow for this case:

> If string is not exactly two characters in length, or if value1 is greater than 59, let most significant units be hours.

The solution would be to update the regular expression to allow for 1 or 2 digits in the hours slot:

    const TIMESTAMP_REGEXP = /([0-9]{1,2})?:?([0-9]{2}):([0-9]{2}\.[0-9]{3})/;

**Comment by alecananian** [comment]
Sorry, I see this has already been fixed.  It looks like the latest version was never pushed to npm, though.  Closing this and will use the latest git commits for my project.

**Comment by osk** [comment]
@alecananian no problem, but it is truly an issue since the package needs updating on NPM, I'm on it

**Comment by osk** [comment]
Updated! Thanks for the report
